services:
  frontend:
    image: lmanarin/frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
      - monitoring
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  backend:
    image: lmanarin/backend:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PHP_FPM_PM=dynamic
      - PHP_FPM_PM_MAX_CHILDREN=30
      - PHP_FPM_PM_START_SERVERS=5
      - PHP_FPM_PM_MIN_SPARE_SERVERS=5
      - PHP_FPM_PM_MAX_SPARE_SERVERS=10
    networks:
      - app-network
    depends_on:
      - mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.my.cnf:/etc/mysql/conf.d/exporter.cnf
    networks:
      - app-network
      - monitoring
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://frontend/nginx_status
    networks:
      - monitoring
      - app-network
    depends_on:
      - frontend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    ports:
      - "9104:9104"
    volumes:
      - ./.my.cnf:/etc/mysqld-exporter/my.cnf
    networks:
      - monitoring
      - app-network
    depends_on:
      - mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M

networks:
  app-network:
    name: docker-project_app-network
  monitoring:
    name: docker-project_monitoring

volumes:
  mysql_data:
    name: docker-project_mysql_data