services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
    networks:
      - app-network
      - monitoring
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    command:
      -nginx.scrape-uri=http://frontend:80/nginx_status    
    networks:
      - monitoring
      - app-network
    depends_on:
      - frontend
    ports:
      - "9113:9113"
    restart: always

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=lucieM:root@(mysql:3306)/ #.my.cnf ?
    volumes:
      - ./.my.cnf:/.my.cnf

    networks:
      - monitoring
      - app-network
    depends_on:
      - mysql
    restart: always

networks:
  app-network:
    name: docker-project_app-network
  monitoring:
    name: docker-project_monitoring

volumes:
  mysql_data:
    name: docker-project_mysql_data