services:
    frontend:
        build: ./frontend
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 256M
        ports:
            - "80:80"
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    backend:
        build: ./backend
        deploy:
            resources:
                limits:
                    cpus: '0.75'
                    memory: 1G
                reservations:
                    cpus: '0.25'
                    memory: 512M
        volumes:
            - ./backend:/var/www/html
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 2G
                reservations:
                    cpus: '0.5'
                    memory: 1G
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: businessCare_docker
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network
