version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network
      - monitoring

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    ports:
      - "9113:9113"
    networks:
      - monitoring

  mysqld-exporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=${DB_USER}:${DB_PASS}@(mysql:3306)/
    networks:
      - monitoring

networks:
  app-network:
  monitoring:

volumes:
  mysql_data: