services:
  frontend:
    image: lmanarin/frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./backend:/var/www/html  # Lier le dossier backend pour accéder aux fichiers PHP
    networks:
      - app-network
      - monitoring
    restart: always
    depends_on:
      - php  # Assurez-vous que frontend dépend de php
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  php:
    image: php:7.4-fpm  # Utiliser une image PHP-FPM
    volumes:
      - ./backend:/var/www/html  # Monter le dossier backend pour exécuter PHP
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  backend:
    image: lmanarin/backend:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PHP_FPM_PM=dynamic
      - PHP_FPM_PM_MAX_CHILDREN=30
      - PHP_FPM_PM_START_SERVERS=5
      - PHP_FPM_PM_MIN_SPARE_SERVERS=5
      - PHP_FPM_PM_MAX_SPARE_SERVERS=10
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network
      - monitoring
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://frontend/nginx_status
    networks:
      - monitoring
      - app-network
    depends_on:
      - frontend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=exporter:Luciole11@@tcp(mysql:3306)/
    networks:
      - monitoring
      - app-network
    depends_on:
      - mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M

networks:
  app-network:
    name: docker-project_app-network
  monitoring:
    name: docker-project_monitoring

volumes:
  mysql_data:
    name: docker-project_mysql_data
