services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: businessCare_docker
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    volumes:
      - ./.my.cnf:/root/.my.cnf
    ports:
      - "9104:9104"
    depends_on:
      - mysql
    networks:
      - app-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - "-nginx.scrape-uri=http://frontend/nginx_status"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  db_data:
