version: '3.8'

services:
  frontend:
    image: lmanarin/frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
      - monitoring
    restart: always

  backend:
    image: lmanarin/backend:latest
    networks:
      - app-network
    depends_on:
      - mysql
    restart: always
    environment:
      - PHP_FPM_PM=dynamic
      - PHP_FPM_PM_MAX_CHILDREN=50
      - PHP_FPM_PM_START_SERVERS=5

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    networks:
      - monitoring
    restart: always

  mysqld-exporter:
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=${MYSQL_EXPORTER_USER}:${MYSQL_EXPORTER_PASSWORD}@(mysql:3306)/
    networks:
      - monitoring
    restart: always

networks:
  app-network:
  monitoring:

volumes:
  mysql_data: